### ISSUE TITLE
feature request - usage without sensor

### ISSUE THREAD

**Issue by camelcamro** [ronniepettersson/homebridge-remootio#13]
Hello,
i know - maybe for safety reasons ... but in my case, there is no safety needed.
why is it not possible to configure remootio without sensor installed ?
maybe for the certification of homebridge - or i see no reason, via the remootio app i can also use it without the OPEN/CLOSE sensor.
pls assist, I'M pretty sure, that I'm not the first one, which would like to have this feature to use remootio (which is great) also without a sensor.
and my motor is not understanding cmd for opening and closing. He only knoiws relay closed is giving an impulse to engage the motor. pls assist before i need to dig into source code

thx cu camel

**Comment by ronniepettersson** [comment]
@camelcamro, 

the main reason to require a sensor was to be able to show the state of the garage door. I will look into your request.

**Comment by camelcamro** [comment]
ok, typically, it is OK, but
remootio is like a remote control tool, which can be used for may many things.
like animal feed rotation system, which only act with a "relay" trigger, and then cycle the next spin, and so on ... so, from my point of view, remootio would limit itself and is not only a door opener, it is much more as that and to a sensor which is not always needed

**Comment by ronniepettersson** [comment]
Hi @camelcamro, 
I agree that the device can be used for many things, but when I purchased the device, it was for my own garage. I am not affiliated with the company Remootio. But, they appreciated that I developed this plug-in, so they added a link to it on their web site.

**Comment by ronniepettersson** [comment]
Implemented in v1.3.4

**Comment by camelcamro** [comment]
greeat, thx, i will try

**Comment by camelcamro** [comment]
Hello,
basically, it is now working, from technical point of view ... but only 2x.
i guess the plugin relay is not changing back the status from "status"
it is like: 
click the button, then the "picture" of the switch (relay) goes to "ON", then after around 5sec, changing back the status to OFF, like a relay switch".
but then i do that again, and then it hangs on status "ON", and then i can't use it again, and need to restart or reload the windows (browser). 
so, i guess the fuctin, which is switching that "ICON" to "OFF" back is somehow buggy. i will test this more with different browser - not sure, where the issue is ...
or maybe another update/fresh of the icon would help, not sure.

**Comment by camelcamro** [comment]
it is strange, it is not always the case, but 90% of the cases the "ICON" stays on "ON" status, and then i can'T use the relay switch again.
tried it with IE; mozilla, chrome, and android homebridge UX web socket
so, it is still buggy. 
funny, a reload of the BROWSER would give me a "OFF" status, and then i can use it again  ...

so, the only bug is, that the "ICON" not (ALWAYS) switching back from state "ON" to "OFF", which blocks another press on the icon to be used

**Comment by ronniepettersson** [comment]
I only tested it with Apple HomeKit, using my iPhone. I did not anticipate using the Homebridge UI for it. I will take a look at that use case.

**Comment by ronniepettersson** [comment]
try to update to v1.3.6.

**Comment by camelcamro** [comment]
thx, seems to be fixed, i will try more with other browsers, but now seems to be working fine 
(tested on android chrome, chrome on windows) => FIXED !
thcx a lot ! great job !!
