### ISSUE TITLE
Remootio not responding in Home app

### ISSUE THREAD

**Issue by ArneTesch** [ronniepettersson/homebridge-remootio#3]
Hi,

I installed and configured the Remootio plugin. In the logs I see the following info:
```
[Remootio] Initializing Remootio platform...
[Remootio] Remootio platform finished initializing!
```

But in the home app, the accessory is not responding.

Do I have to configure something more in the remootio app?

Thanks.

Kind regards,
Arne Tesch

**Comment by ronniepettersson** [comment]
Arne,
The Remootio devices are not auto-discoverable, so first you will have to enable Websocket API for each Remootio device in the Remootio App. Copy the API keys for the next step. 

Thereafter, you will have to configure the Remootio plugin in HomeBridge:
1. Click "Add Remootio device". 
2. Edit Name, IP address, API Secret key and API Auth Key. 
3. Save and restart HomeBridge

Regards,
Ronnie

**Comment by ArneTesch** [comment]
Hi, 

Thanks for the quick reply. 
I did these steps but the accessory is not responding. There are no extra configurations needed in the remootio app?

thanks!

**Comment by ronniepettersson** [comment]
The Remootio device has to be reachable from the HomeBridge device over your LAN/Wi-Fi network. You can try to ping the device from the HomeBridge console to ensure it's reachable. You can also use [wscat](https://github.com/websockets/wscat)  to test if the websocket API is available.

```
> npm install wscat
> wscat -c ws://<IP address of remootio>:8080
```

If you enable debugging in HomeBridge, you will get some extra logging that you can attach here for further troubleshooting.

**Comment by ArneTesch** [comment]
I tried the above command and the output is as follows:

```
hoobs@hoobs:/home/hoobs/.hoobs/etc $ wscat -c ws://192.168.xx.xxx:8080
error: connect ECONNREFUSED 192.168.xx.xxx:8080
> hoobs@hoobs:/home/hoobs/.hoobs/etc $ 
```

Pinging the ip-adress was successful:
```
PING 192.168.xx.xxx (192.168.xx.xxx) 56(84) bytes of data.
64 bytes from 192.168.xx.xxx: icmp_seq=1 ttl=64 time=6.95 ms
64 bytes from 192.168.xx.xxx: icmp_seq=2 ttl=64 time=5.23 ms
64 bytes from 192.168.xx.xxx: icmp_seq=3 ttl=64 time=5.88 ms

--- 192.168.xx.xxx ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 18ms
rtt min/avg/max/mdev = 4.050/5.771/7.514/1.137 ms
```

**Comment by ronniepettersson** [comment]
With that, we can deduct that the websocket API on the Remootio device is not enabled. Check again in the app and ensure it is enabled.

**Comment by ArneTesch** [comment]
Hi,

I disabled and reenabled the websocket API and it works now.

Thanks for the support!
