### ISSUE TITLE
No response in Homekit

### ISSUE THREAD

**Issue by vical22** [ronniepettersson/homebridge-remootio#4]
Hey, I have installed this plug-in but it is shown "No Response" in the Homekit app.
I have installed the status sensor and it works well within the Remootio app.

I have double-checked its IP as well as API keys but all looks correct.

Is there any way I can trouble shoot this?

Thank you.

**Comment by ronniepettersson** [comment]
Hi @vical22, 
A couple of people had issues with the websocket interface on the Remootio device and had to disable/re-enable and finally reboot the device to make it work. 

If that doesn't work, enable debug in Homebridge and post a snippet of your log output. 

Ronnie

**Comment by vical22** [comment]
Hi Ronnie,
Thank you for the quick response.
After resetting the Remootio device as well as websocket interface a couple of times, it is finally working!

Kind regards,

Chris.
