### ISSUE TITLE
Garage will not open/close

### ISSUE THREAD

**Issue by wholly1971** [ronniepettersson/homebridge-remootio#7]
Garage Door won't open and close

In HOOBS its says all connected and initialized

API webhooks enable

But from Home it shows No Response.

The Remootio app works to open and close garage door a 1000km away

Is the problem of not working due to not having sensors connected.

**Comment by ronniepettersson** [comment]
@wholly1971 , the Gate status sensor is required for the plugin to work.  It is spelled out in the Usage section in the README file, but could be more prominent. 

Also, I have not tested the plugin with HOOBS, so I can't provide any guarantees it would work even if you install the sensor.

**Comment by wholly1971** [comment]
Thank you
I thought it would require the sensors, but it was not definitive..

I will install the sensors and see..

**Comment by wholly1971** [comment]
Check that the sensors were installed - YES

Enabled option in Remootio App.

Flipped the Logic switch

Working PERFECTLY in Homekit!

Thankyou!!!
